import { initializeApp } from "firebase/app";
import { getAuth, signInWithCustomToken } from "firebase/auth";
import firebaseConfig from "./firebase.json";

// Initialize Firebase
const app = initializeApp(firebaseConfig);

signInWithCustomToken(
  getAuth(app),
  "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTY2NjE5NTg2OSwiZXhwIjoxNjY2MTk5NDY5LCJpc3MiOiJmaXJlYmFzZS1hdXRoLXRlc3RpbmdAd2lkZXRhZ2dlci5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInN1YiI6ImZpcmViYXNlLWF1dGgtdGVzdGluZ0B3aWRldGFnZ2VyLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwidWlkIjoidHJ1Y0BnbWFpbC5jb20ifQ.MFS8IjGoH-optT4Qj5_2KCrEAGmPboRkZgh5m2BKUPtqYOLBQGPRKI8-xqkmK04-RXmEeaMRGa6MzsYDfMU1sG1Trz4_nSDsBqG6lUkSKhGXXwliLf4ybANGaEJ2Wxr28aRqDaZQmd26WsPesnOYXKW67MMnBAcaQ73ARuVTWzUlcACotXlQcFV-oJONh59-FZYSjY1jstz4SUwqItDqwieQlLTqCg_CPUPWCSGvAGSF_AXjtEt00feivET9wZu-oiMrA9FTcN6qGV3caYmR-oVrVBwj7xEVPaoFZ67j9i6mrkpD5phk_v4gooaeqQoytarY9JgxbN7DeU1f0-nHVw"
).then((user) => {
  console.log(user);
});
